// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/neutron/HHbbbbAnalyzer/80x_v6/TMVA/massOpt/./Limit.C";

#endif
